import Head from 'next/head'
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';

// import favIcon from '../public/assets/fav.png';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hugo Siu | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='../public/assets/fav.png' />
      </Head>
      
      <Main/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact />
    </div>
  )
}
